# Generated by Django 4.2 on 2023-08-25 12:45

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonoCelular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='AbonoImpresora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ActivoInfraestructura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Usado', 'Usado'), ('Roto', 'Roto')], default='Nuevo', max_length=100)),
                ('reparabilidad', models.CharField(blank=True, choices=[('Reparable', 'Reparable'), ('Irreparable', 'Irreparable')], default='Reparable', max_length=100, null=True)),
                ('tipo', models.CharField(default='', max_length=100)),
                ('modelo', models.CharField(default='', max_length=100)),
                ('sn', models.CharField(default='', max_length=100)),
                ('fecha_entrada', models.DateField(default=datetime.date(1, 1, 1))),
                ('area', models.CharField(choices=[('-', '-'), ('PLAN DE AHORRO', 'PLAN DE AHORRO'), ('REPUESTOS', 'REPUESTOS'), ('VENTA DIRECTA 0KM SUC', 'VENTA DIRECTA 0KM SUC'), ('ADM VENTAS', 'ADM VENTAS'), ('SIN CLASIFICAR', 'SIN CLASIFICAR'), ('ADM VENTAS PLANES', 'ADM VENTAS PLANES'), ('SERVICIOS PV', 'SERVICIOS PV'), ('CONTACT C', 'CONTACT C'), ('VENTA DIRECTA 0KM', 'VENTA DIRECTA 0KM'), ('ADM POST VENTA', 'ADM POST VENTA'), ('ADMINISTRACION', 'ADMINISTRACION'), ('ADMINISTRACION CENTRAL', 'ADMINISTRACION CENTRAL'), ('PREENT Y ALISTAJE VN', 'PREENT Y ALISTAJE VN'), ('POST VENTA SERVICIOS', 'POST VENTA SERVICIOS'), ('REPUESTOS SUCURSAL', 'REPUESTOS SUCURSAL'), ('TALLER SUCURSAL', 'TALLER SUCURSAL'), ('PLAN DE AHORRO SUCURSAL', 'PLAN DE AHORRO SUCURSAL'), ('SISTEMAS', 'SISTEMAS'), ('LAVADERO', 'LAVADERO'), ('TALLER', 'TALLER'), ('MKT', 'MKT'), ('COMERCIAL', 'COMERCIAL'), ('GESTORIA', 'GESTORIA'), ('MAESTRANZA', 'MAESTRANZA'), ('VENTA DIRECTA VO', 'VENTA DIRECTA VO'), ('PREENT Y ALISTAJE VO', 'PREENT Y ALISTAJE VO'), ('ADMINISTRACION SUCURSAL', 'ADMINISTRACION SUCURSAL'), ('ADM POST VENTA SUCURSAL', 'ADM POST VENTA SUCURSAL'), ('GERENTE COMERCIAL', 'GERENTE COMERCIAL'), ('ENTREGAS VN', 'ENTREGAS VN')], default='', max_length=100)),
                ('fecha_devolucion', models.DateField(default=datetime.date(1, 1, 1))),
                ('labplg', models.CharField(choices=[('-', '-'), ('IQSA CORDOBA', 'IQSA CORDOBA'), ('AUTOROUTE', 'AUTOROUTE'), ('AVENUE ROSARIO', 'AVENUE ROSARIO'), ('ADMINISTRACION CENTRAL', 'ADMINISTRACION CENTRAL'), ('AILES CABA', 'AILES CABA'), ('AVENUE CORDOBA', 'AVENUE CORDOBA'), ('AMSA MOTORRAD', 'AMSA MOTORRAD'), ('AMSA BMW', 'AMSA BMW'), ('AMSA MINI', 'AMSA MINI'), ('CHEVENT VENADO TUERTO', 'CHEVENT VENADO TUERTO'), ('AVENUE DS', 'AVENUE DS'), ('CHEVENT SALADILLO', 'CHEVENT SALADILLO'), ('VOLANT CENTRAL', 'VOLANT CENTRAL'), ('VOLANT URQUIZA', 'VOLANT URQUIZA')], default='', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Activos de Infraestructura',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(choices=[('FIAT', 'FIAT'), ('RENAULT', 'RENAULT'), ('PEUGEOT', 'PEUGEOT'), ('DS', 'DS'), ('CITROEN', 'CITROEN'), ('BMW', 'BMW'), ('CHEVROLET', 'CHEVROLET')], default='', max_length=100)),
                ('consecionario', models.CharField(choices=[('-', '-'), ('AVEC', 'AVEC'), ('IQSA CORDOBA', 'IQSA CORDOBA'), ('AUTOROUTE', 'AUTOROUTE'), ('CENTRO AUTOMOTORES', 'CENTRO AUTOMOTORES'), ('DS STORE', 'DS STORE'), ('AUTOMUNICH', 'AUTOMUNICH'), ('CHEVENT', 'CHEVENT')], default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('-', '-'), ('PLAN DE AHORRO', 'PLAN DE AHORRO'), ('REPUESTOS', 'REPUESTOS'), ('VENTA DIRECTA 0KM SUC', 'VENTA DIRECTA 0KM SUC'), ('ADM VENTAS', 'ADM VENTAS'), ('SIN CLASIFICAR', 'SIN CLASIFICAR'), ('ADM VENTAS PLANES', 'ADM VENTAS PLANES'), ('SERVICIOS PV', 'SERVICIOS PV'), ('CONTACT C', 'CONTACT C'), ('VENTA DIRECTA 0KM', 'VENTA DIRECTA 0KM'), ('ADM POST VENTA', 'ADM POST VENTA'), ('ADMINISTRACION', 'ADMINISTRACION'), ('ADMINISTRACION CENTRAL', 'ADMINISTRACION CENTRAL'), ('PREENT Y ALISTAJE VN', 'PREENT Y ALISTAJE VN'), ('POST VENTA SERVICIOS', 'POST VENTA SERVICIOS'), ('REPUESTOS SUCURSAL', 'REPUESTOS SUCURSAL'), ('TALLER SUCURSAL', 'TALLER SUCURSAL'), ('PLAN DE AHORRO SUCURSAL', 'PLAN DE AHORRO SUCURSAL'), ('SISTEMAS', 'SISTEMAS'), ('LAVADERO', 'LAVADERO'), ('TALLER', 'TALLER'), ('MKT', 'MKT'), ('COMERCIAL', 'COMERCIAL'), ('GESTORIA', 'GESTORIA'), ('MAESTRANZA', 'MAESTRANZA'), ('VENTA DIRECTA VO', 'VENTA DIRECTA VO'), ('PREENT Y ALISTAJE VO', 'PREENT Y ALISTAJE VO'), ('ADMINISTRACION SUCURSAL', 'ADMINISTRACION SUCURSAL'), ('ADM POST VENTA SUCURSAL', 'ADM POST VENTA SUCURSAL'), ('GERENTE COMERCIAL', 'GERENTE COMERCIAL'), ('ENTREGAS VN', 'ENTREGAS VN')], default='', max_length=100)),
                ('nombre_apellido', models.CharField(default='', max_length=100)),
                ('legajo', models.CharField(default='', max_length=100)),
                ('razon_social', models.CharField(choices=[('-', '-'), ('IQSA S.A.', 'IQSA S.A.'), ('AUTOROUTE S.A.', 'AUTOROUTE S.A.'), ('AVENUE S.A.', 'AVENUE S.A.'), ('AUTO MUNICH S.A.', 'AUTO MUNICH S.A.'), ('AILES S.A.', 'AILES S.A.'), ('CHEVENT S.A.', 'CHEVENT S.A.'), ('VOLANT S.A.', 'VOLANT S.A.')], default='', max_length=100)),
                ('DNI', models.CharField(default='', max_length=100)),
                ('CATEGORIA_CTT', models.CharField(choices=[('-', '-'), ('VEND Y/O PROM DE PLANES', 'VEND Y/O PROM DE PLANES'), ('ESPECIALISTA EN SERVICIOS', 'ESPECIALISTA EN SERVICIOS'), ('VENDEDOR Y/O PROM DE VENTAS', 'VENDEDOR Y/O PROM DE VENTAS'), ('EXCLUIDO DE CONVENIO', 'EXCLUIDO DE CONVENIO'), ('ADM MULTIPLE ESPECIALIZADO', 'ADM MULTIPLE ESPECIALIZADO'), ('ADMINISTRATIVO ESPECIALIZADO', 'ADMINISTRATIVO ESPECIALIZADO'), ('ESPECIALISTA MULT SUP EN SERV', 'ESPECIALISTA MULT SUP EN SERV'), ('ESPECIALISTA SUP. EN SER. MOTO', 'ESPECIALISTA SUP. EN SER. MOTO'), ('ADMINISTRATIVO BASICO', 'ADMINISTRATIVO BASICO'), ('ADMINISTRATIVO AUXILIAR', 'ADMINISTRATIVO AUXILIAR'), ('ADMINISTRATIVO CALIFICADO', 'ADMINISTRATIVO CALIFICADO'), ('ESPECIALISTA SUPERIOR EN SERV', 'ESPECIALISTA SUPERIOR EN SERV'), ('LAVADOR', 'LAVADOR'), ('EXPERTO EN SERVICIOS', 'EXPERTO EN SERVICIOS'), ('AYUDANTE EN SERVICIOS', 'AYUDANTE EN SERVICIOS'), ('MAESTRANZA A', 'MAESTRANZA A')], default='', max_length=100)),
                ('cargo', models.CharField(choices=[('-', '-'), ('VENDEDOR', 'VENDEDOR'), ('SIN CLASIFICAR', 'SIN CLASIFICAR'), ('ADMINISTRATIVO', 'ADMINISTRATIVO'), ('RESPONSABLE ADM PLANES', 'RESPONSABLE ADM PLANES'), ('MECANICO', 'MECANICO'), ('CONTACT C', 'CONTACT C'), ('AUXILIAR', 'AUXILIAR'), ('TECNICO', 'TECNICO'), ('PREPARADOR', 'PREPARADOR'), ('RESPNSABLE COMERCIAL', 'RESPNSABLE COMERCIAL'), ('SUBCONTADOR', 'SUBCONTADOR'), ('SUPERVISOR', 'SUPERVISOR'), ('PREENTREGA Y ALISTAJE', 'PREENTREGA Y ALISTAJE'), ('DESARROLLO INFORMATICO', 'DESARROLLO INFORMATICO'), ('LAVADOR', 'LAVADOR'), ('RESPONSABLE PV', 'RESPONSABLE PV'), ('SOPORTE INFORMATICO', 'SOPORTE INFORMATICO'), ('GERENTE COMERCIAL', 'GERENTE COMERCIAL'), ('ADMINISTRATIVO PV', 'ADMINISTRATIVO PV'), ('CREDITOS', 'CREDITOS'), ('GERENTE PLAN DE AHORRO', 'GERENTE PLAN DE AHORRO'), ('RRHH', 'RRHH'), ('ATENCION AL CLIENTE', 'ATENCION AL CLIENTE'), ('MANAGER PV', 'MANAGER PV'), ('MAESTRANZA', 'MAESTRANZA'), ('GERENTE POST VENTA', 'GERENTE POST VENTA'), ('RESPONSABLE REPUESTOS', 'RESPONSABLE REPUESTOS'), ('GUARDIA DE SEGURIDAD', 'GUARDIA DE SEGURIDAD'), ('JEFE DE TALLER', 'JEFE DE TALLER'), ('CALIDAD', 'CALIDAD'), ('PERITADOR', 'PERITADOR'), ('RESPONSABLE COMERCIAL', 'RESPONSABLE COMERCIAL'), ('ENTREGAS', 'ENTREGAS'), ('REPUESTOS', 'REPUESTOS'), ('JEFATURA REPUESTOS', 'JEFATURA REPUESTOS'), ('GERENTE MKT', 'GERENTE MKT'), ('GESTORIA', 'GESTORIA'), ('CAJA', 'CAJA'), ('DIRECTOR', 'DIRECTOR'), ('GERENTE DE RRHH', 'GERENTE DE RRHH')], default='', max_length=100)),
                ('CCO', models.CharField(choices=[('-', '-'), ('PDA', 'PDA'), ('REPUESTOS', 'REPUESTOS'), ('0KM', '0KM'), ('ADM. COMERCIAL', 'ADM. COMERCIAL'), ('(****)SIN CLASIFICAR', '(****)SIN CLASIFICAR'), ('ADM. PLAN DE AHOROR', 'ADM. PLAN DE AHORRO'), ('TALLER', 'TALLER'), ('MKT', 'MKT'), ('CONT. E IMP.', 'CONT. E IMP.'), ('SISTEMAS', 'SISTEMAS'), ('ADMINISTRACION', 'ADMINISTRACION'), ('PREENTREGA', 'PREENTREGA'), ('USADOS', 'USADOS'), ('AUDITORIAS', 'AUDITORIAS'), ('RRHH', 'RRHH'), ('TESORERIA', 'TESORERIA'), ('COMPRAS', 'COMPRAS'), ('CALIDAD', 'CALIDAD'), ('ESPECIAL', 'ESPECIAL'), ('MANTENIMIENTO', 'MANTENIMIENTO')], default='', max_length=100)),
                ('lugar_trab', models.CharField(choices=[('-', '-'), ('CORDOBA', 'CORDOBA'), ('BUENOS AIRES', 'BUENOS AIRES'), ('SANTA FE', 'SANTA FE'), ('CAPITAL FEDERAL', 'CAPITAL FEDERAL')], default='', max_length=100)),
                ('lab_lpg', models.CharField(choices=[('-', '-'), ('IQSA CORDOBA', 'IQSA CORDOBA'), ('AUTOROUTE', 'AUTOROUTE'), ('AVENUE ROSARIO', 'AVENUE ROSARIO'), ('ADMINISTRACION CENTRAL', 'ADMINISTRACION CENTRAL'), ('AILES CABA', 'AILES CABA'), ('AVENUE CORDOBA', 'AVENUE CORDOBA'), ('AMSA MOTORRAD', 'AMSA MOTORRAD'), ('AMSA BMW', 'AMSA BMW'), ('AMSA MINI', 'AMSA MINI'), ('CHEVENT VENADO TUERTO', 'CHEVENT VENADO TUERTO'), ('AVENUE DS', 'AVENUE DS'), ('CHEVENT SALADILLO', 'CHEVENT SALADILLO'), ('VOLANT URQUIZA', 'VOLANT URQUIZA'), ('VOLANT CENTRAL', 'VOLANT CENTRAL'), ('PEUGEOT CORDOBA', 'PEUGEOT CORDOBA')], default='', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Usado', 'Usado'), ('Roto', 'Roto')], default='Nuevo', max_length=100)),
                ('reparabilidad', models.CharField(blank=True, choices=[('Reparable', 'Reparable'), ('Irreparable', 'Irreparable')], default='Reparable', max_length=100, null=True)),
                ('numero', models.CharField(default='', max_length=100)),
                ('modelo', models.CharField(default='', max_length=100)),
                ('marca', models.CharField(default='', max_length=100)),
                ('fecha_entrada', models.DateField(default=datetime.date(1, 1, 1))),
                ('fecha_devolucion', models.DateField(default=datetime.date(1, 1, 1))),
                ('imei_o_sn', models.CharField(default='', max_length=100)),
                ('accesorio', models.CharField(default='', max_length=100)),
                ('plan', models.CharField(choices=[('-', '-'), ('Plan Control Empresas 1gb', 'Plan Control Empresas 1gb'), ('Empresas Conexion Control M - PERSONAL', 'Empresas Conexion Control M - PERSONAL'), ('Plan Libre Empresas 3gb', 'Plan Libre Empresas 3gb'), ('Plan Libre Empresas 5gb', 'Plan Libre Empresas 5gb'), ('Plan Libre Empresas 8gb', 'Plan Libre Empresas 8gb'), ('Plan Control Empresas 3gb', 'Plan Control Empresas 3gb'), ('Plan Control Empresas 5gb', 'Plan Control Empresas 5gb'), ('Conexion Total Premium XX', 'Conexion Total Premium XX'), ('Plan Control 3GB PC72R', 'Plan Control 3GB PC72R'), ('Plan Control 3GB PC52R', 'Plan Control 3GB PC52R'), ('Plan Control 5GB PC73R', ' Plan Control 5GB PC73R'), ('Plan Control 8GB PC74R', ' Plan Control 8GB PC74R'), ('Plan Control 3GB PC52R - AUTOROUTE', 'Plan Control 3GB PC52R - AUTOROUTE'), ('Plan Control 5GB PC73R - AUTOROUTE', 'Plan Control 5GB PC73R - AUTOROUTE'), ('Plan Control 5GB PC53R - AUTOROUTE', 'Plan Control 5GB PC53R - AUTOROUTE'), ('Plan Control 3GB PC72R - AUTOROUTE', 'Plan Control 3GB PC72R - AUTOROUTE'), ('Plan Control 5GB PC73R - AILES', 'Plan Control 5GB PC73R - AILES'), ('Plan Control 3GB PC72R - AILES', 'Plan Control 3GB PC72R - AILES'), ('Plan Libre 8GB PC74C - AILES', 'Plan Libre 8GB PC74C - AILES'), ('Plan Control 8GB PC54R - AILES', 'Plan Control 8GB PC54R - AILES'), ('Plan Control 5GB PC83R - AILES', 'Plan Control 5GB PC83R - AILES'), ('Plan Control 1GB PC70R - AILES', 'Plan Control 1GB PC70R - AILES'), ('Plan Control 3GB PC52R - AILES', 'Plan Control 3GB PC52R - AILES'), ('Plan Control 5GB PC53R - AILES', 'Plan Control 5GB PC53R - AILES'), ('Plan Control 8GB PC74R - AILES', 'Plan Control 8GB PC74R - AILES'), ('Plan Control 2GB PC71R - AILES', 'Plan Control 2GB PC71R - AILES'), ('Plan Control 3GB PC82R - AILES', 'Plan Control 3GB PC82R - AILES'), ('Plan Control 8GB PC93R - AILES', 'Plan Control 8GB PC93R - AILES')], default='Nuevo', max_length=100)),
                ('empresa_abono', models.CharField(choices=[('SINEMPRESA', 'SIN EMPRESA'), ('PERSONAL', 'PERSONAL'), ('CLARO', 'CLARO')], default='', max_length=100)),
                ('rs', models.CharField(choices=[('-', '-'), ('AMSA', 'PERSONAL - AMSA'), ('AVENUE', 'PERSONAL - AVENUE'), ('VOLANT', 'PERSONAL - VOLANT'), ('IQSA', 'PERSONAL - IQSA'), ('CHEVENT', 'CLARO - CHEVENT'), ('AILES', 'CLARO - AILES'), ('AUTOROUTE', 'CLARO - AUTOROUTE'), ('CLAROAVENUECBA', 'CLARO - AVENUE CORDOBA')], default='Nuevo', max_length=100)),
                ('lablpg', models.CharField(choices=[('-', '-'), ('IQSA CORDOBA', 'IQSA CORDOBA'), ('AUTOROUTE', 'AUTOROUTE'), ('AVENUE ROSARIO', 'AVENUE ROSARIO'), ('ADMINISTRACION CENTRAL', 'ADMINISTRACION CENTRAL'), ('AILES CABA', 'AILES CABA'), ('AVENUE CORDOBA', 'AVENUE CORDOBA'), ('AMSA MOTORRAD', 'AMSA MOTORRAD'), ('AMSA BMW', 'AMSA BMW'), ('AMSA MINI', 'AMSA MINI'), ('CHEVENT VENADO TUERTO', 'CHEVENT VENADO TUERTO'), ('AVENUE DS', 'AVENUE DS'), ('CHEVENT SALADILLO', 'CHEVENT SALADILLO'), ('VOLANT URQUIZA', 'VOLANT URQUIZA'), ('VOLANT CENTRAL', 'VOLANT CENTRAL'), ('PEUGEOT CORDOBA', 'PEUGEOT CORDOBA')], default='', max_length=100)),
                ('usuario', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stock.usuario')),
            ],
            options={
                'verbose_name_plural': 'Telefonos',
            },
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Usado', 'Usado'), ('Roto', 'Roto')], default='Nuevo', max_length=100)),
                ('reparabilidad', models.CharField(blank=True, choices=[('Reparable', 'Reparable'), ('Irreparable', 'Irreparable')], default='Reparable', max_length=100, null=True)),
                ('ram', models.CharField(choices=[('ram2gbddr2', '2GB ddr2'), ('ram2gbddr3', '2GB ddr3'), ('ram4gbddr3', '4GB ddr3'), ('ram8gbddr3', '8GB ddr3'), ('ram12gbddr3', '12 GB ddr3'), ('ram16gbddr3', '16GB ddr3'), ('ram32gbddr3', '32GB ddr3'), ('ram4gb', '4GB ddr4'), ('ram8gb', '8GB ddr4'), ('ram12gbddr4', '12GB ddr4'), ('ram16gb', '16GB ddr4'), ('ram16gb', '32GB ddr4')], default='', max_length=50)),
                ('procesador', models.CharField(choices=[('Celeron', 'Celeron'), ('Pentium', 'Pentium'), ('Intel Core i3 (1ma generacion)', 'Intel Core i3 (1ma generacion)'), ('Intel Core i3 (2ma generacion)', 'Intel Core i3 (2ma generacion)'), ('Intel Core i3 (3ma generacion)', 'Intel Core i3 (3ma generacion)'), ('Intel Core i3 (4ma generacion)', 'Intel Core i3 (4ma generacion)'), ('Intel Core i3 (5ma generacion)', 'Intel Core i3 (5ma generacion)'), ('Intel Core i3 (6ma generacion)', 'Intel Core i3 (6ma generacion)'), ('Intel Core i3 (7ma generacion)', 'Intel Core i3 (7ma generacion)'), ('Intel Core i3 (8va generacion)', 'Intel Core i3 (8va generacion)'), ('Intel Core i3 (9na generacion)', 'Intel Core i3 (9na generacion)'), ('Intel Core i3 (10ma generacion)', 'Intel Core i3 (10ma generacion)'), ('Intel Core i3 (11va generacion)', 'Intel Core i3 (11ma generacion)'), ('Intel Core i3 (12va generacion)', 'Intel Core i3 (12ma generacion)'), ('Intel Core i5 (1ma generacion)', 'Intel Core i5 (1ma generacion)'), ('Intel Core i5 (2ma generacion)', 'Intel Core i5 (2ma generacion)'), ('Intel Core i5 (3ma generacion)', 'Intel Core i5 (3ma generacion)'), ('Intel Core i5 (4ma generacion)', 'Intel Core i5 (4ma generacion)'), ('Intel Core i5 (5ma generacion)', 'Intel Core i5 (5ma generacion)'), ('Intel Core i5 (6ma generacion)', 'Intel Core i5 (6ma generacion)'), ('Intel Core i5 (7ma generacion)', 'Intel Core i5 (7ma generacion)'), ('Intel Core i5 (8va generacion)', 'Intel Core i5 (8va generacion)'), ('Intel Core i5 (9na generacion)', 'Intel Core i5 (9na generacion)'), ('Intel Core i5 (10ma generacion)', 'Intel Core i5 (10ma generacion)'), ('Intel Core i5 (11va generacion)', 'Intel Core i5 (11va generacion)'), ('Intel Core i5 (12va generacion)', 'Intel Core i5 (12va generacion)'), ('Intel Core i7 (8va generacion)', 'Intel Core i7 (8va generacion)'), ('Intel Core i7 (9na generacion)', 'Intel Core i7 (9na generacion)'), ('Intel Core i7 (10ma generacion)', 'Intel Core i7 (10ma generacion)'), ('Intel Core i9 (9na generacion)', 'Intel Core i9 (9na generacion)'), ('Intel Core i9 (10ma generacion)', 'Intel Core i9 (10ma generacion)'), ('AMD Ryzen 3 (1ra generacion)', 'AMD Ryzen 3 (1ra generacion)'), ('AMD Ryzen 3 (2da generacion)', 'AMD Ryzen 3 (2da generacion)'), ('AMD Ryzen 5 (1ra generacion)', 'AMD Ryzen 5 (1ra generacion)'), ('AMD Ryzen 5 (2da generacion)', 'AMD Ryzen 5 (2da generacion)'), ('AMD Ryzen 7 (1ra generacion)', 'AMD Ryzen 7 (1ra generacion)'), ('AMD Ryzen 7 (2da generacion)', 'AMD Ryzen 7 (2da generacion)'), ('AMD Ryzen 9 (1ra generacion)', 'AMD Ryzen 9 (1ra generacion)'), ('AMD Ryzen 9 (2da generacion)', 'AMD Ryzen 9 (2da generacion)'), ('AMD A6', 'AMD A6'), ('AMD A8', 'AMD A8'), ('AMD FX', 'AMD FX'), ('AMD A10', 'AMD A10'), ('AMD A12', 'AMD A12'), ('AMD Athlon', 'AMD Athlon')], default='', max_length=100)),
                ('disco', models.CharField(choices=[('SSD120GB', 'SSD 120 GB'), ('SSD240GB', 'SSD 240 GB'), ('SSD480GB', 'SSD 480 GB'), ('SSD1TB', 'SSD 1 TB'), ('SSD2TB', 'SSD 2 TB'), ('HDD500GB', 'HDD 500 GB'), ('HDD1TGB', 'HDD 1TB '), ('HDD2T', 'HDD 2TB'), ('HDD3TB', 'HDD 3TB'), ('HDD4TB', 'HDD 4TB')], default='', max_length=50)),
                ('mouse', models.CharField(default='', max_length=100)),
                ('mousesn', models.CharField(default='', max_length=100)),
                ('teclado', models.CharField(default='', max_length=100)),
                ('tecladosn', models.CharField(default='', max_length=100)),
                ('monitor', models.CharField(choices=[('-', '-'), ('LG', 'LG'), ('SAMSUNG', 'SAMSUNG'), ('LENOVO', 'LENOVO'), ('NETSYS', 'NETSYS'), ('CX', 'CX'), ('HP', 'HP'), ('BENQ', 'BENQ'), ('NOBLEX', 'NOBLEX'), ('PHILIPS', 'PHILIPS'), ('VIEWSONIC', 'VIEWSONIC'), ('E-VIEW', 'E-VIEW'), ('CORADIR', 'CORADIR'), ('2151AXA', '2151AXA'), ('ACER', 'ACER')], default='', max_length=100)),
                ('modelo', models.CharField(choices=[('clon', 'Clon'), ('lenovo', 'Lenovo'), ('hp', 'HP'), ('asus', 'Asus'), ('xpg', 'Xpg'), ('dell', 'Dell'), ('acer', 'Acer'), ('macbook', 'Macbook'), ('samsung', 'Samsung'), ('vaio', 'Vaio'), ('sony', 'Sony'), ('SENTEY', 'Sentey'), ('BANGHO', 'Bangho'), ('OVERTECH', 'Overtech'), ('BRB', 'Brb'), ('MUSTIFF', 'Mustiff'), ('CX', 'CX'), ('Magnum', 'Magnum'), ('Coradir', 'Coradir'), ('SOLARMAX', 'SOLARMAX')], default='', max_length=100)),
                ('sn', models.CharField(max_length=100)),
                ('antiguedad', models.CharField(default='', max_length=100)),
                ('fecha_entrada', models.DateField(default=datetime.date(1, 1, 1))),
                ('fecha_devolucion', models.DateField(default=datetime.date(1, 1, 1))),
                ('lablpg', models.CharField(choices=[('-', '-'), ('IQSA CORDOBA', 'IQSA CORDOBA'), ('AUTOROUTE', 'AUTOROUTE'), ('AVENUE ROSARIO', 'AVENUE ROSARIO'), ('ADMINISTRACION CENTRAL', 'ADMINISTRACION CENTRAL'), ('AILES CABA', 'AILES CABA'), ('AVENUE CORDOBA', 'AVENUE CORDOBA'), ('AMSA MOTORRAD', 'AMSA MOTORRAD'), ('AMSA BMW', 'AMSA BMW'), ('AMSA MINI', 'AMSA MINI'), ('CHEVENT VENADO TUERTO', 'CHEVENT VENADO TUERTO'), ('AVENUE DS', 'AVENUE DS'), ('CHEVENT SALADILLO', 'CHEVENT SALADILLO'), ('VOLANT CENTRAL', 'VOLANT CENTRAL'), ('VOLANT URQUIZA', 'VOLANT URQUIZA')], default='', max_length=100)),
                ('usuario', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stock.usuario')),
            ],
            options={
                'verbose_name_plural': 'PCs',
            },
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(choices=[('hp', 'HP'), ('asus', 'Asus'), ('lenovo', 'Lenovo'), ('xpg', 'Xpg'), ('dell', 'Dell'), ('acer', 'Acer'), ('macbook', 'Macbook'), ('samsung', 'Samgung'), ('vaio', 'Vaio'), ('sony', 'Sony'), ('bangho', 'Bangho'), ('gigabyte', 'Gigabyte')], default='marca1', max_length=100)),
                ('procesador', models.CharField(choices=[('Celeron', 'Celeron'), ('Pentium', 'Pentium'), ('Intel Core i3 (1ma generacion)', 'Intel Core i3 (1ma generacion)'), ('Intel Core i3 (2ma generacion)', 'Intel Core i3 (2ma generacion)'), ('Intel Core i3 (3ma generacion)', 'Intel Core i3 (3ma generacion)'), ('Intel Core i3 (4ma generacion)', 'Intel Core i3 (4ma generacion)'), ('Intel Core i3 (5ma generacion)', 'Intel Core i3 (5ma generacion)'), ('Intel Core i3 (6ma generacion)', 'Intel Core i3 (6ma generacion)'), ('Intel Core i3 (7ma generacion)', 'Intel Core i3 (7ma generacion)'), ('Intel Core i3 (8va generacion)', 'Intel Core i3 (8va generacion)'), ('Intel Core i3 (9na generacion)', 'Intel Core i3 (9na generacion)'), ('Intel Core i3 (10ma generacion)', 'Intel Core i3 (10ma generacion)'), ('Intel Core i3 (11va generacion)', 'Intel Core i3 (11ma generacion)'), ('Intel Core i3 (12va generacion)', 'Intel Core i3 (12ma generacion)'), ('Intel Core i5 (1ma generacion)', 'Intel Core i5 (1ma generacion)'), ('Intel Core i5 (2ma generacion)', 'Intel Core i5 (2ma generacion)'), ('Intel Core i5 (3ma generacion)', 'Intel Core i5 (3ma generacion)'), ('Intel Core i5 (4ma generacion)', 'Intel Core i5 (4ma generacion)'), ('Intel Core i5 (5ma generacion)', 'Intel Core i5 (5ma generacion)'), ('Intel Core i5 (6ma generacion)', 'Intel Core i5 (6ma generacion)'), ('Intel Core i5 (7ma generacion)', 'Intel Core i5 (7ma generacion)'), ('Intel Core i5 (8va generacion)', 'Intel Core i5 (8va generacion)'), ('Intel Core i5 (9na generacion)', 'Intel Core i5 (9na generacion)'), ('Intel Core i5 (10ma generacion)', 'Intel Core i5 (10ma generacion)'), ('Intel Core i5 (11va generacion)', 'Intel Core i5 (11va generacion)'), ('Intel Core i5 (12va generacion)', 'Intel Core i5 (12va generacion)'), ('Intel Core i7 (2da generacion)', 'Intel Core i7 (2da generacion)'), ('Intel Core i7 (8va generacion)', 'Intel Core i7 (8va generacion)'), ('Intel Core i7 (9na generacion)', 'Intel Core i7 (9na generacion)'), ('Intel Core i7 (10ma generacion)', 'Intel Core i7 (10ma generacion)'), ('Intel Core i7 (11va generacion)', 'Intel Core i7 (11va generacion)'), ('Intel Core i7 (12va generacion)', 'Intel Core i7 (12va generacion)'), ('Intel Core i9 (9na generacion)', 'Intel Core i9 (9na generacion)'), ('Intel Core i9 (10ma generacion)', 'Intel Core i9 (10ma generacion)'), ('AMD Ryzen 3 (1ra generacion)', 'AMD Ryzen 3 (1ra generacion)'), ('AMD Ryzen 3 (2da generacion)', 'AMD Ryzen 3 (2da generacion)'), ('AMD Ryzen 5 (1ra generacion)', 'AMD Ryzen 5 (1ra generacion)'), ('AMD Ryzen 5 (2da generacion)', 'AMD Ryzen 5 (2da generacion)'), ('AMD Ryzen 7 (1ra generacion)', 'AMD Ryzen 7 (1ra generacion)'), ('AMD Ryzen 7 (2da generacion)', 'AMD Ryzen 7 (2da generacion)'), ('AMD Ryzen 9 (1ra generacion)', 'AMD Ryzen 9 (1ra generacion)'), ('AMD Ryzen 9 (2da generacion)', 'AMD Ryzen 9 (2da generacion)'), ('AMD A6', 'AMD A6'), ('AMD A8', 'AMD A8'), ('AMD A10', 'AMD A10'), ('AMD A12', 'AMD A12')], default='procesador1', max_length=100)),
                ('ram', models.CharField(choices=[('ram4gbddr3', '4GB ddr3'), ('ram8gbddr3', '8GB ddr3'), ('ram12gbddr3', '12GB ddr3'), ('ram16gbddr3', '16GB ddr3'), ('ram32gbddr3', '32GB ddr3'), ('ram4gb', '4GB ddr4'), ('ram8gb', '8GB ddr4'), ('ram12gbddr4', '12GB ddr4'), ('ram16gb', '16GB ddr4'), ('ram32gb', '32GB ddr4')], default='ram4gb', max_length=50)),
                ('disco', models.CharField(choices=[('SSD120GB', 'SSD 120 GB'), ('SSD240GB', 'SSD 240 GB'), ('SSD480GB', 'SSD 480 GB'), ('SSD1TB', 'SSD 1 TB'), ('SSD2TB', 'SSD 2 TB'), ('HDD500GB', 'HDD 500 GB'), ('HDD1TGB', 'HDD 1TB '), ('HDD2T', 'HDD 2TB'), ('HDD3TB', 'HDD 3TB'), ('HDD4TB', 'HDD 4TB')], default='disco128gb', max_length=50)),
                ('estado', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Usado', 'Usado'), ('Roto', 'Roto')], default='Nuevo', max_length=100)),
                ('reparabilidad', models.CharField(blank=True, choices=[('Reparable', 'Reparable'), ('Irreparable', 'Irreparable')], default='Reparable', max_length=100, null=True)),
                ('monitor', models.CharField(choices=[('monitor13', '13 pulgadas'), ('monitor15', '15 pulgadas'), ('monitor17', '17 pulgadas'), ('monitor17', '22 pulgadas'), ('monitor17', '24 pulgadas'), ('monitor17', '27 pulgadas'), ('monitor17', '32 pulgadas')], default='', max_length=100)),
                ('lablpg', models.CharField(choices=[('-', '-'), ('IQSA CORDOBA', 'IQSA CORDOBA'), ('AUTOROUTE', 'AUTOROUTE'), ('AVENUE ROSARIO', 'AVENUE ROSARIO'), ('ADMINISTRACION CENTRAL', 'ADMINISTRACION CENTRAL'), ('AILES CABA', 'AILES CABA'), ('AVENUE CORDOBA', 'AVENUE CORDOBA'), ('AMSA MOTORRAD', 'AMSA MOTORRAD'), ('AMSA BMW', 'AMSA BMW'), ('AMSA MINI', 'AMSA MINI'), ('CHEVENT VENADO TUERTO', 'CHEVENT VENADO TUERTO'), ('AVENUE DS', 'AVENUE DS'), ('CHEVENT SALADILLO', 'CHEVENT SALADILLO'), ('VOLANT CENTRAL', 'VOLANT CENTRAL'), ('VOLANT URQUIZA', 'VOLANT URQUIZA')], default='', max_length=100)),
                ('modelo', models.CharField(default='', max_length=100)),
                ('mouse', models.CharField(default='', max_length=100)),
                ('mousesn', models.CharField(default='', max_length=100)),
                ('sn', models.CharField(default='', max_length=100)),
                ('antiguedad', models.CharField(default='', max_length=100)),
                ('fecha_entrada', models.DateField(default=datetime.date(1, 1, 1))),
                ('fecha_devolucion', models.DateField(default=datetime.date(1, 1, 1))),
                ('usuario', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stock.usuario')),
            ],
            options={
                'verbose_name_plural': 'Notebooks',
            },
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licenciaoffice', models.CharField(choices=[('microsoftteamsroomspro', 'Microsft Teams Rooms Pro'), ('office365E5', 'Office 365 E5'), ('office365E5WAC', 'Office 365 E5 without Audio Conferencing'), ('exchangeonlineplan1', 'Exchange Online (Plan 1)'), ('exchangeonlinekiosk', 'Exchange Online Kiosk'), ('office365e1', 'Office 365 E1')], max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.usuario')),
            ],
            options={
                'verbose_name_plural': 'Licencias',
            },
        ),
        migrations.CreateModel(
            name='Impresora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Usado', 'Usado'), ('Roto', 'Roto')], default='Nuevo', max_length=100)),
                ('reparabilidad', models.CharField(blank=True, choices=[('Reparable', 'Reparable'), ('Irreparable', 'Irreparable')], default='Reparable', max_length=100, null=True)),
                ('tipo', models.CharField(choices=[('Alquilada', 'Alquilada'), ('Propia', 'Propia')], default='', max_length=100)),
                ('modelo', models.CharField(default='', max_length=100)),
                ('abono', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)])),
                ('sn', models.CharField(default='', max_length=100)),
                ('plan', models.CharField(choices=[('SIN PLAN', 'SIN PLAN'), ('Multifuncion RICOH IM 430f PEUGEOT', 'Multifuncion RICOH IM 430f - PEUGEOT CBA'), ('Impresora RICOH SP 4510dn PEUGEOT', 'Impresora RICOH SP 4510dn - PEUGEOT CBA'), ('Multifuncion BROTHER DCPL5650dn PEUGEOT', 'Multifuncion BROTHER DCPL5650dn - PEUGEOT CBA'), ('Multifuncion BROTHER MFCL2720DW PEUGEOT', 'Multifuncion BROTHER MFCL2720dw - PEUGEOT CBA'), ('Impresora BROTHER HL-L5100DN PEUGEOT', 'Impresora BROTHER HL-L5100DN - PEUGEOT CBA'), ('Impresora RICOH P311 PEUGEOT', 'Impresora RICOH P311 - PEUGEOT CBA'), ('Multifuncion RICOH IM 430f IQSA', 'Multifuncion RICOH IM 430f - CITROEN CBA'), ('Impresora RICOH SP 4510dn IQSA', 'Impresora RICOH SP 4510dn - CITROEN CBA'), ('Multifuncion LEXMARK XM5170 IQSA', 'Multifuncion LEXMARK XM5170 - CITROEN CBA'), ('Multifuncion BROTHER MFCL2720dw IQSA', 'Multifuncion BROTHER MFCL2720dw - CITROEN CBA'), ('Multifuncion RICOH IM C2000 IQSA', 'Multifuncion RICOH IM C2000 - CITROEN CBA'), ('Multifuncion BROTHER DCPL5650dn IQSA', 'Multifuncion BROTHER DCPL5650dn - CITROEN CBA')], default='Nuevo', max_length=100)),
                ('antiguedad', models.CharField(default='', max_length=100)),
                ('fecha_entrada', models.DateField(default=datetime.date(1, 1, 1))),
                ('fecha_devolucion', models.DateField(default=datetime.date(1, 1, 1))),
                ('lablpg', models.CharField(choices=[('-', '-'), ('IQSA CORDOBA', 'IQSA CORDOBA'), ('AUTOROUTE', 'AUTOROUTE'), ('AVENUE ROSARIO', 'AVENUE ROSARIO'), ('ADMINISTRACION CENTRAL', 'ADMINISTRACION CENTRAL'), ('AILES CABA', 'AILES CABA'), ('AVENUE CORDOBA', 'AVENUE CORDOBA'), ('AMSA MOTORRAD', 'AMSA MOTORRAD'), ('AMSA BMW', 'AMSA BMW'), ('AMSA MINI', 'AMSA MINI'), ('CHEVENT VENADO TUERTO', 'CHEVENT VENADO TUERTO'), ('AVENUE DS', 'AVENUE DS'), ('CHEVENT SALADILLO', 'CHEVENT SALADILLO'), ('VOLANT CENTRAL', 'VOLANT CENTRAL'), ('VOLANT URQUIZA', 'VOLANT URQUIZA')], default='', max_length=100)),
                ('usuario', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stock.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo_tipo', models.CharField(choices=[('Telefono', 'Telefono'), ('Notebook', 'Notebook'), ('Escritorio', 'Escritorio'), ('Impresora', 'Impresora'), ('ActivoInfraestructura', 'ActivoInfraestructura')], default='defCargo', max_length=100)),
                ('activo_id', models.PositiveIntegerField()),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('Rotura', 'Rotura'), ('Actualizacion', 'Actualizacion'), ('Perdida', 'Perdida'), ('Baja', 'Baja')], max_length=100)),
                ('descripcion', models.TextField()),
                ('dado_de_baja', models.BooleanField(default=False)),
                ('motivo_baja', models.TextField(blank=True)),
                ('impresora', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stock.impresora')),
                ('notebook', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stock.notebook')),
                ('pc', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stock.pc')),
                ('telefono', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stock.telefono')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('usuario', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stock.usuario')),
            ],
            options={
                'verbose_name_plural': 'Historial de Activos',
            },
        ),
        migrations.CreateModel(
            name='EliminacionTelefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_eliminacion', models.CharField(max_length=100)),
                ('fecha_eliminacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario_ant', models.CharField(max_length=100)),
                ('telefono', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stock.telefono')),
                ('usuario_eliminacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='EliminacionPc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_eliminacion', models.CharField(max_length=100)),
                ('fecha_eliminacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario_ant', models.CharField(max_length=100)),
                ('pc', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stock.pc')),
                ('usuario_eliminacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='EliminacionNotebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_eliminacion', models.CharField(max_length=100)),
                ('fecha_eliminacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario_ant', models.CharField(max_length=100)),
                ('notebook', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stock.notebook')),
                ('usuario_eliminacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='EliminacionImpresora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_eliminacion', models.CharField(max_length=100)),
                ('fecha_eliminacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario_ant', models.CharField(max_length=100)),
                ('impresora', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stock.impresora')),
                ('usuario_eliminacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='EliminacionActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_eliminacion', models.CharField(max_length=100)),
                ('fecha_eliminacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario_ant', models.CharField(max_length=100)),
                ('activo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stock.activoinfraestructura')),
                ('usuario_eliminacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='AltaTelefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateTimeField(default=django.utils.timezone.now)),
                ('telefono', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stock.telefono')),
                ('usuario_alta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='AltaPc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateTimeField(default=django.utils.timezone.now)),
                ('pc', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stock.pc')),
                ('usuario_alta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='AltaNotebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateTimeField(default=django.utils.timezone.now)),
                ('notebook', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stock.notebook')),
                ('usuario_alta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='AltaImpresora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateTimeField(default=django.utils.timezone.now)),
                ('impresora', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stock.impresora')),
                ('usuario_alta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='AltaActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateTimeField(default=django.utils.timezone.now)),
                ('activo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stock.activoinfraestructura')),
                ('usuario_alta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='activoinfraestructura',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stock.usuario'),
        ),
    ]
